/** Declaration file generated by dts-gen */

export = lyric_parser;

declare class lyric_parser {
    constructor(lrc: any, ...args: any[]);

    play(...args: any[]): void;

    seek(offset: any): void;

    stop(): void;

    togglePlay(): void;

}

declare namespace lyric_parser {
    namespace prototype {
        function play(...args: any[]): void;

        function seek(offset: any): void;

        function stop(): void;

        function togglePlay(): void;

        namespace play {
            const prototype: {
            };

        }

        namespace seek {
            const prototype: {
            };

        }

        namespace stop {
            const prototype: {
            };

        }

        namespace togglePlay {
            const prototype: {
            };

        }

    }

}

